language: node_js
node_js:
  - "12.8.0"
cache:
  directories:
    - "node_modules"
script:
  - npm test
  - npm run build
  - npm run build:site
after_success:
  - npm run report-coverage
notifications:
  slack: g-explorer:81CbfYw9kEml7k1QcXQkGfrB
